"""Two-compartment current-based spiking neurons.

This module implements a compact soma-apical neuron with:

- a fast somatic GLIF-like membrane state,
- a slow apical current state with a nonlinear plateau,
- bidirectional soma-apical coupling via scalar currents.

The implementation follows btorch's stateful-module conventions so that the
membrane voltage and apical state can be initialized, reset, detached, and
tracked during truncated BPTT.
"""

from collections.abc import Callable, Sequence
from typing import Any, Literal

import torch
from jaxtyping import Float
from torch import Tensor

from ...types import TensorLike
from .. import environ
from ..base import MemoryModule, ParamBufferMixin, is_broadcastable, normalize_n_neuron
from ..surrogate import ATan


class TwoCompartmentGLIF(ParamBufferMixin, MemoryModule):
    """Two-compartment current-based neuron with apical plateaus.

    The model combines a fast somatic compartment with a slow apical current:

    .. math::
        \\tau_s \\frac{dV_s}{dt} =
        -(V_s - E_L) + R_s \\left(I_{soma} + w_{as} I_a\\right) +
        \\Delta_T \\exp\\left(\\frac{V_s - V_{th,eff}}{\\Delta_T}\\right)

    .. math::
        \\tau_a \\frac{dI_a}{dt} =
        -I_a + I_{apical} +
        w_{Ca} \\sigma(I_a - \\theta_{Ca}) + I_{bap}

    Somatic spikes are generated by a surrogate threshold on ``V_s`` and stored
    as a pending back-propagating current for the next timestep.

    A minimal adaptive threshold state can optionally be enabled:

    .. math::
        V_{th,eff} = V_{th} + \\theta_h

    .. math::
        \\tau_h \\frac{d\\theta_h}{dt} = -\\theta_h

    followed by an instantaneous post-spike increment
    :math:`\\theta_h \\leftarrow \\theta_h + \\Delta_h`.

    Args:
        n_neuron: Number of neurons, as an ``int`` or tuple of neuron axes.
        v_threshold: Somatic spike threshold.
        v_reset: Somatic reset voltage after a spike.
        tau_s: Somatic membrane time constant.
        R_s: Somatic input resistance.
        E_L: Somatic leak reversal / resting voltage.
        tau_a: Apical current time constant.
        tau_th: Adaptive-threshold decay time constant.
        delta_th: Post-spike threshold increment.
        delta_T: Exponential spike-initiation scale. Set to zero to disable.
        w_Ca: Calcium plateau amplitude.
        theta_Ca: Apical plateau activation threshold.
        w_sa: Somatic-to-apical coupling weight for the delayed bAP current.
        w_as: Apical-to-somatic coupling weight for top-down drive.
        trainable_param: Names of parameters to optimize.
        surrogate_function: Surrogate gradient function for soma spikes.
        detach_reset: If ``True``, detach the reset signal from the graph.
        step_mode: ``"s"`` for single-step or ``"m"`` for multi-step dispatch.
        backend: Backend label for consistency with other neuron modules.
        device: Optional torch device.
        dtype: Optional torch dtype.

    Attributes:
        v: Somatic membrane voltage memory.
        i_a: Slow apical current memory.
        i_bap: Pending back-propagating current injected on the next step.
        theta_th: Adaptive threshold memory added to ``v_threshold``.

    Examples:
        >>> from btorch.models import environ, functional
        >>> neuron = TwoCompartmentGLIF(n_neuron=1)
        >>> functional.init_net_state(neuron, batch_size=2)
        >>> with environ.context(dt=1.0):
        ...     spike, voltage = neuron.single_step_forward(
        ...         torch.zeros(2, 1),
        ...         torch.zeros(2, 1),
        ...     )
        >>> tuple(spike.shape), tuple(voltage.shape)
        ((2, 1), (2, 1))

    Notes:
        The integration uses a semi-implicit Euler update: the leak / decay
        term is treated implicitly while external and coupling currents are
        evaluated from the previous state. This keeps the update stable while
        preserving a simple differentiable recurrence.
    """

    v: torch.Tensor
    i_a: torch.Tensor
    i_bap: torch.Tensor
    theta_th: torch.Tensor

    v_threshold: torch.Tensor | torch.nn.Parameter
    v_reset: torch.Tensor | torch.nn.Parameter
    tau_s: torch.Tensor | torch.nn.Parameter
    R_s: torch.Tensor | torch.nn.Parameter
    E_L: torch.Tensor | torch.nn.Parameter
    tau_a: torch.Tensor | torch.nn.Parameter
    tau_th: torch.Tensor | torch.nn.Parameter
    delta_th: torch.Tensor | torch.nn.Parameter
    delta_T: torch.Tensor | torch.nn.Parameter
    w_Ca: torch.Tensor | torch.nn.Parameter
    theta_Ca: torch.Tensor | torch.nn.Parameter
    w_sa: torch.Tensor | torch.nn.Parameter
    w_as: torch.Tensor | torch.nn.Parameter

    def __init__(
        self,
        n_neuron: int | Sequence[int],
        *,
        v_threshold: float | Float[TensorLike, " n_neuron"] = -50.0,
        v_reset: float | Float[TensorLike, " n_neuron"] = -65.0,
        tau_s: float | Float[TensorLike, " n_neuron"] = 20.0,
        R_s: float | Float[TensorLike, " n_neuron"] = 1.0,
        E_L: float | Float[TensorLike, " n_neuron"] = -70.0,
        tau_a: float | Float[TensorLike, " n_neuron"] = 100.0,
        tau_th: float | Float[TensorLike, " n_neuron"] = 50.0,
        delta_th: float | Float[TensorLike, " n_neuron"] = 0.0,
        delta_T: float | Float[TensorLike, " n_neuron"] = 0.0,
        w_Ca: float | Float[TensorLike, " n_neuron"] = 0.0,
        theta_Ca: float | Float[TensorLike, " n_neuron"] = 1.0,
        w_sa: float | Float[TensorLike, " n_neuron"] = 0.5,
        w_as: float | Float[TensorLike, " n_neuron"] = 1.0,
        trainable_param: set[str] = set(),
        surrogate_function: Callable = ATan(),
        detach_reset: bool = False,
        step_mode: Literal["s", "m"] = "s",
        backend: Literal["torch"] = "torch",
        device=None,
        dtype=None,
    ):
        super().__init__()
        self.n_neuron, self.size = normalize_n_neuron(n_neuron)
        self.trainable_param = set(trainable_param)
        self.surrogate_function = surrogate_function
        self.detach_reset = detach_reset
        self.step_mode = step_mode
        self.backend = backend

        self.register_memory("v", v_reset, self.n_neuron)
        self.register_memory("i_a", 0.0, self.n_neuron)
        self.register_memory("i_bap", 0.0, self.n_neuron)
        self.register_memory("theta_th", 0.0, self.n_neuron)

        factory_kwargs: dict[str, Any] = {"device": device, "dtype": dtype}
        for name, value in (
            ("v_threshold", v_threshold),
            ("v_reset", v_reset),
            ("tau_s", tau_s),
            ("R_s", R_s),
            ("E_L", E_L),
            ("tau_a", tau_a),
            ("tau_th", tau_th),
            ("delta_th", delta_th),
            ("delta_T", delta_T),
            ("w_Ca", w_Ca),
            ("theta_Ca", theta_Ca),
            ("w_sa", w_sa),
            ("w_as", w_as),
        ):
            self.def_param(
                name,
                value,
                sizes=self.n_neuron,
                trainable_param=self.trainable_param,
                **factory_kwargs,
            )

    def _prepare_step_tensor(
        self,
        x: float | Tensor,
        *,
        name: str,
    ) -> Float[Tensor, "*batch n_neuron"]:
        target = self.v
        x = torch.as_tensor(x, device=target.device, dtype=target.dtype)
        if x.shape == target.shape:
            return x
        if x.numel() == 1:
            return torch.full_like(target, x.reshape(()))
        if is_broadcastable(x.shape, target.shape):
            return torch.broadcast_to(x, target.shape)
        raise RuntimeError(
            f"{name} shape mismatch. Expected a tensor broadcastable to "
            f"{tuple(target.shape)}, got {tuple(x.shape)}."
        )

    @staticmethod
    def _positive(x: Tensor, eps: float = 1e-4) -> Tensor:
        return torch.clamp(x, min=eps)

    def _plateau_current(self) -> Float[Tensor, "*batch n_neuron"]:
        return self.w_Ca * torch.sigmoid(self.i_a - self.theta_Ca)

    def _update_apical_current(
        self,
        i_apical: Float[Tensor, "*batch n_neuron"],
        dt: float,
    ) -> Float[Tensor, "*batch n_neuron"]:
        tau_a = self._positive(self.tau_a)
        drive = i_apical + self._plateau_current() + self.i_bap
        decay = dt / tau_a
        return (self.i_a + decay * drive) / (1.0 + decay)

    def _update_somatic_voltage(
        self,
        i_soma: Float[Tensor, "*batch n_neuron"],
        i_a_next: Float[Tensor, "*batch n_neuron"],
        threshold_eff: Float[Tensor, "*batch n_neuron"],
        dt: float,
    ) -> Float[Tensor, "*batch n_neuron"]:
        tau_s = self._positive(self.tau_s)
        R_s = self._positive(self.R_s)
        total_current = i_soma + self.w_as * i_a_next
        delta_T = torch.clamp(self.delta_T, min=0.0)
        exp_arg = torch.clamp(
            (self.v - threshold_eff) / torch.clamp(delta_T, min=1e-4),
            max=10.0,
        )
        exp_drive = torch.where(
            delta_T > 0.0,
            delta_T * torch.exp(exp_arg),
            torch.zeros_like(self.v),
        )
        decay = dt / tau_s
        numerator = self.v + decay * (self.E_L + R_s * total_current + exp_drive)
        return numerator / (1.0 + decay)

    def _reset_voltage(
        self,
        v_pre_spike: Float[Tensor, "*batch n_neuron"],
        spike: Float[Tensor, "*batch n_neuron"],
    ) -> Float[Tensor, "*batch n_neuron"]:
        spike_d = spike.detach() if self.detach_reset else spike
        return v_pre_spike - (v_pre_spike - self.v_reset) * spike_d

    def _update_threshold_state(
        self,
        spike: Float[Tensor, "*batch n_neuron"],
        dt: float,
    ) -> Float[Tensor, "*batch n_neuron"]:
        tau_th = self._positive(self.tau_th)
        decay = dt / tau_th
        spike_d = spike.detach() if self.detach_reset else spike
        return self.theta_th / (1.0 + decay) + self.delta_th * spike_d

    def single_step_forward(
        self,
        i_soma: Float[Tensor | float, "*batch n_neuron"],
        i_apical: Float[Tensor | float, "*batch n_neuron"] | None = None,
        *,
        return_state: bool = False,
    ) -> tuple[Tensor, Tensor] | tuple[Tensor, Tensor, dict[str, Tensor]]:
        """Advance the neuron by one timestep.

        Args:
            i_soma: Somatic current input.
            i_apical: Optional apical current input. Defaults to zero.
            return_state: If ``True``, also return a state dictionary.

        Returns:
            A tuple ``(spike, voltage)``. When ``return_state=True``, returns
            ``(spike, voltage, state_dict)`` with ``v_pre_spike``, ``i_a``, and
            ``i_bap`` traces for the current step.
        """
        dt = float(environ.get("dt"))
        soma_drive = self._prepare_step_tensor(i_soma, name="i_soma")
        apical_drive = (
            torch.zeros_like(soma_drive)
            if i_apical is None
            else self._prepare_step_tensor(i_apical, name="i_apical")
        )

        i_a_next = self._update_apical_current(apical_drive, dt)
        threshold_eff = self.v_threshold + self.theta_th
        v_pre_spike = self._update_somatic_voltage(
            soma_drive,
            i_a_next,
            threshold_eff,
            dt,
        )
        spike = self.surrogate_function(v_pre_spike - threshold_eff)

        self.i_a = i_a_next
        self.v = self._reset_voltage(v_pre_spike, spike)
        self.i_bap = self.w_sa * spike
        self.theta_th = self._update_threshold_state(spike, dt)

        if not return_state:
            return spike, self.v

        return spike, self.v, {
            "v": self.v,
            "v_pre_spike": v_pre_spike,
            "i_a": self.i_a,
            "i_bap": self.i_bap,
            "theta_th": self.theta_th,
            "v_threshold_eff": threshold_eff,
        }

    def multi_step_forward(
        self,
        i_soma_seq: Float[Tensor, "T *batch n_neuron"],
        i_apical_seq: Float[Tensor, "T *batch n_neuron"] | None = None,
        *,
        return_state: bool = False,
    ) -> tuple[Tensor, Tensor] | tuple[Tensor, Tensor, dict[str, Tensor]]:
        """Advance the neuron over a full input sequence."""
        spike_seq = []
        v_seq = []
        v_pre_seq = []
        i_a_seq = []
        i_bap_seq = []
        theta_th_seq = []
        threshold_seq = []

        for t in range(i_soma_seq.shape[0]):
            step_apical = None if i_apical_seq is None else i_apical_seq[t]
            step_out = self.single_step_forward(
                i_soma_seq[t],
                step_apical,
                return_state=return_state,
            )
            if return_state:
                spike_t, v_t, state_t = step_out
                v_pre_seq.append(state_t["v_pre_spike"])
                i_a_seq.append(state_t["i_a"])
                i_bap_seq.append(state_t["i_bap"])
                theta_th_seq.append(state_t["theta_th"])
                threshold_seq.append(state_t["v_threshold_eff"])
            else:
                spike_t, v_t = step_out
            spike_seq.append(spike_t)
            v_seq.append(v_t)

        spike_seq_t = torch.stack(spike_seq, dim=0)
        v_seq_t = torch.stack(v_seq, dim=0)
        if not return_state:
            return spike_seq_t, v_seq_t

        return spike_seq_t, v_seq_t, {
            "v": v_seq_t,
            "v_pre_spike": torch.stack(v_pre_seq, dim=0),
            "i_a": torch.stack(i_a_seq, dim=0),
            "i_bap": torch.stack(i_bap_seq, dim=0),
            "theta_th": torch.stack(theta_th_seq, dim=0),
            "v_threshold_eff": torch.stack(threshold_seq, dim=0),
        }

    def forward(
        self,
        i_soma: Tensor,
        i_apical: Tensor | None = None,
        *,
        return_state: bool = False,
    ) -> tuple[Tensor, Tensor] | tuple[Tensor, Tensor, dict[str, Tensor]]:
        """Dispatch to single-step or multi-step forward."""
        if self.step_mode == "m":
            return self.multi_step_forward(
                i_soma,
                i_apical,
                return_state=return_state,
            )
        return self.single_step_forward(
            i_soma,
            i_apical,
            return_state=return_state,
        )

    def extra_repr(self) -> str:
        parts = [
            f"n_neuron={self.n_neuron}",
            f"step_mode={self.step_mode}",
            f"backend={self.backend}",
            f"surrogate={self.surrogate_function.__class__.__name__}",
        ]
        mem_repr = MemoryModule.extra_repr(self)
        if mem_repr:
            parts.append(mem_repr)
        return ", ".join(parts)


__all__ = ["TwoCompartmentGLIF"]
